apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terraria.fullname" . }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
data:
  serverconfig.txt: > 
    {{ range $key, $value := .Values.terraria.serversettings }}
    {{$key}}={{ $value }}
    {{ end }}