apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terraria.fullname" . }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "terraria.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terraria.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "terraria.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        - name: worlds
          {{- if .Values.world.persistentVolume.enabled }}
          persistentVolumeClaim:
            {{- if .Values.world.persistentVolume.existingClaim }}
            claimName: {{ .Values.world.persistentVolume.existingClaim }}
            {{- else }}
            claimName: {{ include "terraria.fullname" . }}
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 7777
              name: server
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
