apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraria.fullname" . }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: server
      name: server
      protocol: TCP
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "terraria.selectorLabels" . | nindent 4 }}